# Generated by Django 4.1.7 on 2023-03-20 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppKaliz', '0003_alfajor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Torta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('peso', models.FloatField()),
            ],
        ),
    ]
