# Generated by Django 4.1.7 on 2023-03-22 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppKaliz', '0005_sandwiche_delete_clientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sandwiche',
            name='sabor',
            field=models.CharField(max_length=30),
        ),
    ]
