# Generated by Django 4.1.7 on 2023-04-03 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppKaliz', '0006_alter_sandwiche_sabor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaPublicacion', models.DateTimeField(auto_now_add=True)),
                ('duracion', models.IntegerField()),
                ('nombreReceta', models.CharField(max_length=30)),
                ('breveDescripcion', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagenRecetaDulce', models.ImageField(blank=True, null=True, upload_to='ImagenesUsuarios')),
                ('ingredientes', models.CharField(max_length=200)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['usuario', '-fechaPublicacion'],
            },
        ),
        migrations.DeleteModel(
            name='Alfajor',
        ),
        migrations.DeleteModel(
            name='Alfajores',
        ),
    ]
