# Generated by Django 4.1.7 on 2023-04-03 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppKaliz', '0008_rename_imagenrecetadulce_recetas_imagenreceta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recetas',
            name='imagenReceta',
            field=models.ImageField(blank=True, null=True, upload_to='media/ImagenesUsuarios'),
        ),
    ]
