# Generated by Django 4.1.7 on 2023-04-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppKaliz', '0009_alter_recetas_imagenreceta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recetas',
            name='imagenReceta',
            field=models.ImageField(blank=True, null=True, upload_to='ImagenesUsuarios'),
        ),
    ]
