# Generated by Django 4.1.7 on 2023-04-05 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppKaliz', '0014_alter_recetas_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recetas',
            old_name='duracion',
            new_name='Duracion',
        ),
        migrations.RenameField(
            model_name='recetas',
            old_name='imagenReceta',
            new_name='Imagen',
        ),
        migrations.RenameField(
            model_name='recetas',
            old_name='ingredientes',
            new_name='Ingredientes',
        ),
        migrations.RenameField(
            model_name='recetas',
            old_name='breveDescripcion',
            new_name='Pasos',
        ),
        migrations.RenameField(
            model_name='recetas',
            old_name='nombreReceta',
            new_name='Receta',
        ),
    ]
