# Generated by Django 4.1.7 on 2023-04-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppKaliz', '0015_rename_duracion_recetas_duracion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recetas',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='recetas',
            name='Pasos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recetas',
            name='Descripcion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
