# Generated by Django 4.1.7 on 2023-04-05 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppKaliz', '0016_remove_recetas_descripcion_alter_recetas_pasos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecetasDulces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaPublicacion', models.DateTimeField(auto_now_add=True)),
                ('Duracion', models.IntegerField()),
                ('Receta', models.CharField(max_length=30)),
                ('Descripcion', models.CharField(blank=True, max_length=50, null=True)),
                ('Pasos', models.TextField(blank=True, null=True)),
                ('Imagen', models.ImageField(blank=True, null=True, upload_to='media/ImagenesUsuarios')),
                ('Ingredientes', models.CharField(max_length=200)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Sandwiche',
        ),
        migrations.DeleteModel(
            name='Torta',
        ),
        migrations.DeleteModel(
            name='Tortas',
        ),
    ]
