# Generated by Django 4.1.7 on 2023-04-05 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.fields.related


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppKaliz', '0017_recetasdulces_delete_sandwiche_delete_torta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recetas',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.fields.related.ForeignKey, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recetasdulces',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.fields.related.ForeignKey, to=settings.AUTH_USER_MODEL),
        ),
    ]
