# Generated by Django 4.1.7 on 2023-04-07 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppKaliz', '0019_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='fechaPublicacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='usuario',
            field=models.TextField(max_length=30),
        ),
    ]
